image: maven:3.3.9

pipelines:
  branches:
    master:
      - step:
          caches:
            - maven
          script:
            - mvn -B deploy 
    develop:
      - step:
          caches:
            - maven
          script: 
            - mvn -B deploy 